default: &default
  adapter: postgresql
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: cutie_switches_development

test:
  <<: *default
  database: cutie_switches_test

production:
  <<: *default
  database: cutie_switches_production
